service: first-serverless-aws-project
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  region: eu-central-1

plugins:
  - serverless-s3-sync
  
custom:
  s3Sync:
    - bucketName: serverless-tutorial-bucket-2q439w749357
      localDir: UploadData

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: serverless-tutorial-bucket-2q439w749357